### ISSUE TITLE
__init__() got an unexpected keyword argument 'tags' with python 3.6.8

### ISSUE THREAD

**Issue by ricardosalazarcab** [bstriner/gym-env-traffic#4]
I have the next error, in the example: "example_gym_traffic_dqn". Could you help me? 

Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Python3.6.8\scripts\gym-traffic-master\examples\example_gym_traffic_dqn.py 
Traceback (most recent call last):
  File "C:\Python3.6.8\scripts\gym-traffic-master\examples\example_gym_traffic_dqn.py", line 4, in <module>
    from gym_traffic.agents import DQN, EpsilonExplorer
  File "C:\Users\RICARDO\AppData\Local\Programs\Python\Python36\lib\site-packages\gym_traffic-0.0.1-py3.6.egg\gym_traffic\__init__.py", line 8, in <module>
    nondeterministic=True
  File "C:\Users\RICARDO\AppData\Local\Programs\Python\Python36\lib\site-packages\gym\envs\registration.py", line 139, in register
    return registry.register(id, **kwargs)
  File "C:\Users\RICARDO\AppData\Local\Programs\Python\Python36\lib\site-packages\gym\envs\registration.py", line 133, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tags'

**Comment by agbulutonur** [comment]
I had the same issue while running the example.

**Comment by SHITIANYU-hue** [comment]
I had the same issue while running the example.

**Comment by EricSchuMa** [comment]
Check this out https://github.com/openai/roboschool/issues/208

**Comment by TheMedicineSeller** [comment]
Same error while running `examples/example_gym_traffic_random.py` , is downgrading to an older gym version the only possible cure ?
Also if i don't want to downgrade, is it good enough to comment out the `tags=` argument in `__init__()` in the `setup.py` file ?
